### PR TITLE
Improve compiler options

### PR DESCRIPTION
**Pull request by juancarlospaco**

### CODE REVIEW

**Comment by PMunch** [comment]
This breaks the layout on small screens, mostly because of the horrible way I implemented the options bar into the layout.. But that doesn't really matter much as the back-end doesn't support any of the extra options passed in, so changing them won't actually do anything..

**Comment by juancarlospaco** [comment]
https://github.com/PMunch/nim-playground/blob/master/test/script.sh#L13 :grey_question: 
What else is needed for it to work, maybe point me to where it needs to be changed.

The options are chopped off on small screen, but that was pre-existing anyway, but thats CSS.

**Comment by PMunch** [comment]
Yeah, that line in the script along with the `docker_timeout.sh` and [where it is called on the backend](https://github.com/PMunch/nim-playground/blob/master/src/nim_playground.nim#L98-L100). What do you mean it appears to work? If you try to e.g. add a `when defined(release)` and set it to release mode it doesn't trigger. The other arguments are simply lost on their way to the script as it is only meant to pass a single argument.

The options are not chopped off any longer, at least not until you reach sub 250px width. At least not in my testing. The current system for the option bar is however a bit too brittle, it should be implemented in a better way.

**Comment by juancarlospaco** [comment]
Then I will close this, and think about something with more UX, kinda like https://play.rust-lang.org

**Comment by PMunch** [comment]
I like the idea of that config pop-up. That would look great!

**Comment by juancarlospaco** [comment]
I think one problem we had in general all over Nim, is that we are repeatng manual CSS ll over again with each service/project, just copying the Nim brand colors for theme.

At https://nimwc.org we researched *a lot* the topic of CSS, 
finding CSS frameworks that are tiny and No-JavaScript required at all, DRY,
maybe we can make a theme for it (just changing base color variables and recompiling).

- https://bulma.io No JavaScript, easy to use
- https://picturepan2.github.io/spectre/experimentals.html No JavaScript, lot of widgets, not so easy
- https://kognise.github.io/water.css No JavaScript, No classes on HTML

I will try a UI with Bulma and Nim colors.

**Pull request closed without merging**
